// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using Microsoft.VisualStudio.TestTools.UnitTesting;


        [TestClass]
        public class OperacionesGeneralesTest
        {
            private IWebDriver driver;
            public IDictionary<string, object> vars { get; private set; }
            private IJavaScriptExecutor js;
            [TestInitialize]
            public void SetUp()
            {
                driver = new RemoteWebDriver(new Uri("http://localhost:4444/wd/hub"), new ChromeOptions().ToCapabilities());
                js = (IJavaScriptExecutor)driver;
                vars = new Dictionary<string, object>();
            }
            [TestCleanup]
            public void TearDown()
            {
                driver.Quit();
            }
            [TestMethod]
            public void multiplesOperaciones()
            {
                // Test name: MúltiplesOperaciones
                // Step # | name | target | value
                // 1 | open | / | 
                driver.Navigate().GoToUrl("https://www.calculadoraonline.org/");
                // 2 | setWindowSize | 1096x689 | 
                driver.Manage().Window.Size = new System.Drawing.Size(1096, 689);
                // 3 | click | css=.clear | 
                driver.FindElement(By.CssSelector(".clear")).Click();
                // 4 | click | css=.number:nth-child(18) | 
                driver.FindElement(By.CssSelector(".number:nth-child(18)")).Click();
                // 5 | click | css=.operation:nth-child(28) | 
                driver.FindElement(By.CssSelector(".operation:nth-child(28)")).Click();
                // 6 | click | css=.number:nth-child(18) | 
                driver.FindElement(By.CssSelector(".number:nth-child(18)")).Click();
                // 7 | click | css=.operation:nth-child(14) | 
                driver.FindElement(By.CssSelector(".operation:nth-child(14)")).Click();
                // 8 | click | css=.number:nth-child(19) | 
                driver.FindElement(By.CssSelector(".number:nth-child(19)")).Click();
                // 9 | click | css=.operation:nth-child(7) | 
                driver.FindElement(By.CssSelector(".operation:nth-child(7)")).Click();
                // 10 | click | css=.number:nth-child(19) | 
                driver.FindElement(By.CssSelector(".number:nth-child(19)")).Click();
                // 11 | click | name=enter | 
                driver.FindElement(By.Name("enter")).Click();
                // 12 | assertValue | name=display | 2
                {
                    string value = driver.FindElement(By.Name("display")).GetAttribute("value");
                    Assert.AreEqual(value, "2");
                }
                // 13 | close |  | 
                driver.Close();
            }
            [TestMethod]
            public void puedeBorrarContenidoConLetraC()
            {
                // Test name: PuedeBorrarContenidoConLetraC
                // Step # | name | target | value
                // 1 | open | / | 
                driver.Navigate().GoToUrl("https://www.calculadoraonline.org/");
                // 2 | setWindowSize | 1096x833 | 
                driver.Manage().Window.Size = new System.Drawing.Size(1096, 833);
                // 3 | click | css=.number:nth-child(12) | 
                driver.FindElement(By.CssSelector(".number:nth-child(12)")).Click();
                // 4 | click | css=.operation:nth-child(14) | 
                driver.FindElement(By.CssSelector(".operation:nth-child(14)")).Click();
                // 5 | click | css=.number:nth-child(5) | 
                driver.FindElement(By.CssSelector(".number:nth-child(5)")).Click();
                // 6 | click | css=.number:nth-child(11) | 
                driver.FindElement(By.CssSelector(".number:nth-child(11)")).Click();
                // 7 | click | name=enter | 
                driver.FindElement(By.Name("enter")).Click();
                // 8 | click | css=.clear | 
                driver.FindElement(By.CssSelector(".clear")).Click();
                // 9 | assertValue | name=display | 0
                {
                    string value = driver.FindElement(By.Name("display")).GetAttribute("value");
                    Assert.AreEqual(value, "0");
                }
                // 10 | click | css=.number:nth-child(12) | 
                driver.FindElement(By.CssSelector(".number:nth-child(12)")).Click();
                // 11 | click | css=.number:nth-child(5) | 
                driver.FindElement(By.CssSelector(".number:nth-child(5)")).Click();
                // 12 | click | css=.number:nth-child(13) | 
                driver.FindElement(By.CssSelector(".number:nth-child(13)")).Click();
                // 13 | click | css=.number:nth-child(6) | 
                driver.FindElement(By.CssSelector(".number:nth-child(6)")).Click();
                // 14 | click | css=.operation:nth-child(14) | 
                driver.FindElement(By.CssSelector(".operation:nth-child(14)")).Click();
                // 15 | click | css=.number:nth-child(12) | 
                driver.FindElement(By.CssSelector(".number:nth-child(12)")).Click();
                // 16 | click | css=.number:nth-child(4) | 
                driver.FindElement(By.CssSelector(".number:nth-child(4)")).Click();
                // 17 | click | css=.number:nth-child(5) | 
                driver.FindElement(By.CssSelector(".number:nth-child(5)")).Click();
                // 18 | click | css=form | 
                driver.FindElement(By.CssSelector("form")).Click();
                // 19 | click | name=enter | 
                driver.FindElement(By.Name("enter")).Click();
                // 20 | click | css=.clear | 
                driver.FindElement(By.CssSelector(".clear")).Click();
                // 21 | close |  | 
                driver.Close();
            }
        }
