// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using Microsoft.VisualStudio.TestTools.UnitTesting;

[TestClass]
public class OperacionesBasicasTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [TestInitialize]
  public void SetUp() {
    driver = new RemoteWebDriver(new Uri("http://localhost:4444/wd/hub"), new ChromeOptions().ToCapabilities());
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TestCleanup]
  public void TearDown() {
        /// Comentario.
    driver.Quit();
  }
  [TestMethod]
  public void divide70por7Igual10() {
    // Test name: Divide70por7Igual10
    // Step # | name | target | value
    // 1 | open | / | 
    driver.Navigate().GoToUrl("https://www.calculadoraonline.org/");
    // 2 | setWindowSize | 970x1045 | 
    driver.Manage().Window.Size = new System.Drawing.Size(970, 1045);
    // 3 | click | css=.number:nth-child(4) | 
    driver.FindElement(By.CssSelector(".number:nth-child(4)")).Click();
    // 4 | click | css=.number:nth-child(26) | 
    driver.FindElement(By.CssSelector(".number:nth-child(26)")).Click();
    // 5 | click | css=.operation:nth-child(7) | 
    driver.FindElement(By.CssSelector(".operation:nth-child(7)")).Click();
    // 6 | click | css=.number:nth-child(4) | 
    driver.FindElement(By.CssSelector(".number:nth-child(4)")).Click();
    // 7 | click | name=enter | 
    driver.FindElement(By.Name("enter")).Click();
    // 8 | assertValue | name=display | 10
    {
      string value = driver.FindElement(By.Name("display")).GetAttribute("value");
      Assert.AreEqual(value, "10");
    }
    // 9 | close |  | 
    driver.Close();
  }
  [TestMethod]
  public void multiplica7por5Igual35() {
    // Test name: Multiplica7por5Igual35
    // Step # | name | target | value
    // 1 | open | / | 
    driver.Navigate().GoToUrl("https://www.calculadoraonline.org/");
    // 2 | setWindowSize | 970x1045 | 
    driver.Manage().Window.Size = new System.Drawing.Size(970, 1045);
    // 3 | click | css=.number:nth-child(4) | 
    driver.FindElement(By.CssSelector(".number:nth-child(4)")).Click();
    // 4 | click | css=.operation:nth-child(14) | 
    driver.FindElement(By.CssSelector(".operation:nth-child(14)")).Click();
    // 5 | click | css=.number:nth-child(12) | 
    driver.FindElement(By.CssSelector(".number:nth-child(12)")).Click();
    // 6 | click | name=enter | 
    driver.FindElement(By.Name("enter")).Click();
    // 7 | assertValue | name=display | 35
    {
      string value = driver.FindElement(By.Name("display")).GetAttribute("value");
      Assert.AreEqual(value, "35");
    }
    // 8 | close |  | 
    driver.Close();
  }
  [TestMethod]
  public void resta70Menos50Igual20() {
    // Test name: Resta70Menos50Igual20
    // Step # | name | target | value
    // 1 | open | / | 
    driver.Navigate().GoToUrl("https://www.calculadoraonline.org/");
    // 2 | setWindowSize | 985x776 | 
    driver.Manage().Window.Size = new System.Drawing.Size(985, 776);
    // 3 | click | css=.number:nth-child(4) | 
    driver.FindElement(By.CssSelector(".number:nth-child(4)")).Click();
    // 4 | click | css=.number:nth-child(26) | 
    driver.FindElement(By.CssSelector(".number:nth-child(26)")).Click();
    // 5 | click | css=.operation:nth-child(21) | 
    driver.FindElement(By.CssSelector(".operation:nth-child(21)")).Click();
    // 6 | click | css=.number:nth-child(12) | 
    driver.FindElement(By.CssSelector(".number:nth-child(12)")).Click();
    // 7 | click | css=.number:nth-child(26) | 
    driver.FindElement(By.CssSelector(".number:nth-child(26)")).Click();
    // 8 | click | name=enter | 
    driver.FindElement(By.Name("enter")).Click();
    // 9 | assertValue | name=display | 20
    {
      string value = driver.FindElement(By.Name("display")).GetAttribute("value");
      Assert.AreEqual(value, "20");
    }
    // 10 | close |  | 
    driver.Close();
  }
  [TestMethod]
  public void suma70Mas50Igual120() {
    // Test name: Suma70Mas50Igual120
    // Step # | name | target | value
    // 1 | open | / | 
    driver.Navigate().GoToUrl("https://www.calculadoraonline.org/");
    // 2 | setWindowSize | 974x1040 | 
    driver.Manage().Window.Size = new System.Drawing.Size(974, 1040);
    // 3 | click | css=.number:nth-child(4) | 
    driver.FindElement(By.CssSelector(".number:nth-child(4)")).Click();
    // 4 | click | css=.number:nth-child(26) | 
    driver.FindElement(By.CssSelector(".number:nth-child(26)")).Click();
    // 5 | click | css=.operation:nth-child(28) | 
    driver.FindElement(By.CssSelector(".operation:nth-child(28)")).Click();
    // 6 | click | css=.number:nth-child(12) | 
    driver.FindElement(By.CssSelector(".number:nth-child(12)")).Click();
    // 7 | click | css=.number:nth-child(26) | 
    driver.FindElement(By.CssSelector(".number:nth-child(26)")).Click();
    // 8 | click | name=enter | 
    driver.FindElement(By.Name("enter")).Click();
    // 9 | assertValue | name=display | 120
    {
      string value = driver.FindElement(By.Name("display")).GetAttribute("value");
      Assert.AreEqual(value, "120");
    }
    // 10 | close |  | 
    driver.Close();
  }
}
