name: .NET 4.5

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: Setup .NET 4.5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install MS-Build
      run: Import-Module -Name "MsBuild"
    - name: Build solution
      run: Invoke-MsBuild -Path $Env:GITHUB_WORKSPACE\Calculadora.sln
    - name: Test
      run: dotnet test --no-restore --verbosity normal
